name: Build
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
      - uses: cachix/cachix-action@v10
        with:
          name: autophagy
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Nix Build
        run: nix-build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
          cname: tid.autophagy.io
