name: Test
on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'test'
        run: 'echo $TEST'
        env:
          TEST: ${{ secrets.SECRET_THAT_DOESNT_EXIST }}
